### ISSUE TITLE
Change Jade

### ISSUE THREAD

**Issue by Revod** [KrisOlszewski/web-starter-kit-gulp#1]
Hi, i want to use your repo, but its possible to change from Jade to HTML?, im very newbie, thank for that

**Comment by kris-ellery** [comment]
It would be possible, but requires quite a bit of rewriting. This repo is more of a starting point for anyone who wants to modify it and make it work to their needs. You can use Grunt version (https://github.com/KrisOlszewski/web-starter-kit) which uses Handlebars and you can write plain old HTML.

**Comment by Revod** [comment]
Yeah, i try to rewrite for that, thanks anyway, i will find in google because i use gulp

**Comment by kris-ellery** [comment]
Let me know if this branch works for you: https://github.com/KrisOlszewski/web-starter-kit-gulp/tree/html

**Comment by Revod** [comment]
Oh @KrisOlszewski thankssss, i try to install and in this point no procced. stuck from 2h ago. why?
![fasm](https://cloud.githubusercontent.com/assets/10109689/8423229/fa3dc6e2-1eaf-11e5-847d-a3397d6021ab.png)

**Comment by kris-ellery** [comment]
Unfortunately, I do not use Windows and have no idea how to debug it. You would have to check which package installation is failing and raise an issue with its author.
